spring:
  datasource:
    url: "jdbc:h2:file:/data/ecomm_order"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# HTTP Server (Tomcat) Port
server:
  port: 3333
