spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_service

  jpa:
    hibernate:
      ddl-auto: update
    # Display JPA sql DDL/DML at output screen for debugging purpose
    show-sql: true

  application:
    name: product-service # Service Name (Eureka service id is all capital letters.)

# Use to invoke schema.sql and data.sql each time application is started
#  sql:
#    init:
#      mode: always

# Eureka Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 0

# See schema.sql and data.sql SQL statements in the application log
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus

# For setting the distributed tracing samples to 100%
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans