spring:
  data:
    mongodb:
      uri: mongodb://product-service-MongoDB:27017/product_service

# Eureka Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

# For setting the distributed tracing samples to 100%
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

server:
  port: 8080
