spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: devuser
    password: hangzhoU@1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Display JPA sql DDL/DML at output screen for debugging purpose
    show-sql: true

  application:
    name: inventory-service # Service Name (Eureka service id is all capital letters.)

# Use to invoke schema.sql and data.sql each time application is started
#  sql:
#    init:
#      mode: always

# Eureka Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 0

# For setting the distributed tracing samples to 100%
management:
  tracing:
    sampling:
      probability: 1.0

# Actuator Prometheus endpoint
  endpoints:
    web:
      exposure:
        include: prometheus

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

